name: CustomBook
main: com.tenth.custombook.BookCommandExec
version: 1.0
commands:
  customBook:
    description: Give sender the book.
    usage: /customBook <book>
    permission: customBook.giveSelf
  giveCustomBook:
    description: Gives another player the book.
    usage: /giveCustomBook <playerName> <book>
    permission: customBook.giveOthers
permissions:
  customBook.giveOthers:
    default: op
  customBook.giveSelf:
    default: not op